### ISSUE TITLE
pelux.io/download.md page links to different SWF documents

### ISSUE THREAD

**Issue by jeremiah** [Pelagicore/pelux.io#57]
On this page: http://pelux.io/downloads/ there are two links to the software factory; one at line 9 and another at line 69. If you're a user and you're trying to build PELUX from source for the Intel platform and you take the first link at line 9, you wind up at this page --> http://pelux.io/software-factory/v1.0/

If you use the URL at line 69, you wind up here -->http://pelux.io/software-factory/master/chapters/baseplatform/index.html 

This is confusing. Which is the 'canonical' set of instructions? Should one only use software-factory/v1.0/ to build PELUX 1.0 (there's a certain logic there.) 

Sorry for being pedantic but the second link above shows a documentation version in the upper left corner as being "2.0-alpha" and in the URL you can see the term "master" used. For the SWF 1.0 it has "1.0" as a version in both the URL and in the document itself. This consistency is pleasing.

**Comment by tobsan** [comment]
Master will always point to the latest, which currently is 2.0-alpha. I think this confusion could be due to bad CSS. The first links that point to 1.0 are for the release of PELUX 1.0. The link for building from source is a generic link independent of release version, and therefore it points to master.

So yes, one should use the 1.0 docs to build PELUX 1.0. For the latest one should use master. I'll see if we can make the CSS clearer wrt header sizes.

**Comment by tobsan** [comment]
This has been fixed through #63. Closing.
